name: CI Runner

on: [push]

env:
  PROJECT_ROOT: ${{github.workspace}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Compilation Image
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: ${{github.workspace}}/build_scripts/build.sh

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ${{github.workspace}}/build_temp/Testing/**/*.xml