name: CI Runner

on: [push]

env:
  PROJECT_ROOT: ${{github.workspace}}

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Compilation Image
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: ${{github.workspace}}/build_scripts/build.sh

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: ./build_temp/Testing/**/*.xml

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./build_temp/code_coverage.xml # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)