name: CI Runner

on: [push]

env:
  PROJECT_ROOT: ${{github.workspace}}

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build And Test
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: ${{github.workspace}}/build_scripts/build.sh

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ${{github.workspace}}/build_temp/coverage_report.xml # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)